### ISSUE TITLE
Does not launch via Lutris with 2.0 update

### ISSUE THREAD

**Issue by area** [PathOfBuildingCommunity/PathOfBuilding-Launcher#3]
I know that you don't officially support WINE, but I'm hoping that there is a simple enough fix for you here.

With the 2.0 update, when launching through WINE, (more specifically, via Lutris) I get the error:

`ERROR: Could not find a valid launcher lua file.`

This is resolved, and the app launches, if I add the full path to `Launch.lua` as an argument, bypassing the discovery code in the launcher. This is obviously a possible long-term solution for those of us on Linux, but hopefully there is an easy fix if there is a change in behaviour here that was unintended.

**Comment by Wires77** [comment]
I'm not at all familiar with Lutris, but this does work in Wine itself.  How/Where does Lutris install/run PoB compared to wine?

**Comment by area** [comment]
Hm, you're correct. It even works running through the `lutris-wrapper` script from the command line:

```
WINE_PREFIX=/home/$USER/Games/path-of-building /usr/share/lutris/bin/lutris-wrapper Pob 0 0 /home/$USER/.local/share/lutris/runners/wine/lutris-6.4-x86_64/bin/wine "/home/$USER/Games/path-of-building/Path of Building.exe"
```

 which suggests it's something in the Lutris GUI which is extra-confusing...

**Comment by Wires77** [comment]
The new launcher looks in several places for the Launch.lua file.  It first checks the command line parameter, then the same directory as the .exe, followed by Window-specific locations, like the registry and %AppData%.

I'll put Lutris on my VM when I get some time and see if I can figure out how the files get setup, but if you're able to modify the wrapper script to add the location of `Launch.lua` as a commandline parameter, that should work

**Comment by Wires77** [comment]
I installed Lutris on my VM, PoB opened up and updated to 2.0.3 just fine.  I was also able to run it by going to Configure > Game Options and putting "/home/wires77/Games/path-of-building/Launch.lua" in the Arguments box.  Hopefully that works for you, but outside of that there's not much we can do on our end, so I'm going to close this issue.
